language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_script: cd premium
script:
  - npm run test:unit
after_script:
  - cat ./coverage/lcov.info | coveralls
branches:
  only:
  - otherbuild

