language: node_js
node_js:
  - 8
script:
  - cd premium
cache:
  directories:
    - node_modules
script:
  - npm run test:unit
after_script:
  - cat ./coverage/lcov.info | coveralls
branches:
  only:
  - otherbuild

